### PR TITLE
SQSCANNER-100 - Upgrade github-action_release to v4

### PR DESCRIPTION
**Pull request by belen-pruvost-sonarsource**

### CODE REVIEW

**Review by tobias-trabelsi-sonarsource — CHANGES_REQUESTED** [review]
i think we need add an additional step:
```
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.BINARIES_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.BINARIES_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.BINARIES_AWS_REGION }}
```

**Comment by belen-pruvost-sonarsource** [comment]
Thanks @tobias-trabelsi-sonarsource for catching that. Should that step be done for both jobs (`run_release` and `maven-central-sync`)?

**Comment by tobias-trabelsi-sonarsource** [comment]
@belen-pruvost-sonarsource `run_release` should be okay

**Review by tobias-trabelsi-sonarsource — APPROVED** [review]
LGTM

**Pull request merged**
