### PR TITLE
SQSCANNER-78 - backtick syntax

### PR DESCRIPTION
**Pull request by mark-rekveld-sonarsource**
In response to https://community.sonarsource.com/t/sonarqube-scanner-failing-with-syntax-error-at-line-16-target-unexpected/6424/5

### CODE REVIEW

**Comment by dbmeneses** [comment]
@janos-ss Calling in the shell scripting expert :) Any down sides in moving to bash?

**Comment by janosgyerik** [comment]
Hm, not sure this is a good idea. For example OSX is deprecating bash in favor of zsh, though it will probably take some years before they remove `/bin/bash`. Also take a look at the `gradlew` generated in Gradle projects, they use `sh`, not `bash`. Probably others too, probably for good reason.

I think it would be safer to stick with `/bin/sh`, and replace the `$(...)` with the archaic backtick syntax (yikes). I posted a [question](https://community.sonarsource.com/t/sonarqube-scanner-failing-with-syntax-error-at-line-16-target-unexpected/6424/11) on the community because I'm curious where they found such shell where this is a problem :-/

**Comment by mark-rekveld-sonarsource** [comment]
@janos-ss Do you have a sec to take a look at this PR?

**Review by janosgyerik — APPROVED** [review]
Looks good to me, didn't test.

**Pull request merged**
