### PR TITLE
SQSCANNER-67 - Warn on duplicate property definitions

### PR DESCRIPTION
**Pull request by mark-rekveld-sonarsource**
SQSCANNER-67

### CODE REVIEW

**Review by mickael-caro-sonarsource — APPROVED** [review]
Was trying the wrong exec, that's the reason why it was not working on my side :) LGTM !

**Review by mickael-caro-sonarsource — CHANGES_REQUESTED** [review]
In fact i have a question : If we pass more than 2 parameters with the same name, only the 2 first will be shown in the warn. What about maybe listing all the properties with the same name, and say : ok we take only the first one passed, and the others are ignored ?

**Comment by mark-rekveld-sonarsource** [comment]
The logic looks at the properties that are existing to determine if the new value is overriding an existing value.

So the following steps are taken, so take the example that the `foo=bar`, `foo=baz`, `foo=value` are :
 - first it adds `foo` with value `bar`, no issue since there is no existing value for `foo`
 - next it adds `foo` with value `baz`, issue found, the previous value was `bar` so it logs old value `bar` and new value `baz`
 - next it adds `foo` with value `value`, issue found, this time it overrides the value set in step 2, so it logs old value `baz` and new value `value`

In the end the value of `foo` is `value` and is was overridden twice, each override having a log message.

Keep in mind that parsing of the CLI parameters is done without any knowledge of the entire parameter list. Only the elements processed and the current element being processes are known. Possible future elements in the list are not known and thus cannot be checked.

**Comment by mickael-caro-sonarsource** [comment]
Makes sense, thanks !

**Review by mickael-caro-sonarsource — APPROVED** [review]

**Pull request merged**
