### PR TITLE
Added glob expansions for sonar.sources, sonar.jacoco.reportPaths, so…

### PR DESCRIPTION
**Pull request by chaochichen**
Added glob expansions for sonar.sources, sonar.jacoco.reportPaths, , sonar.scala.coverage.reportPaths, and sonar.java.binaries properties before invoking the embedded scanner.

### CODE REVIEW

**Comment by janos-ss** [comment]
Can you please tell us more about the use case? Does this solve a practical problem for you?

At a glance, this is a major change to the behavior of these properties: it replaces a simple list of explicit paths with directory tree traversal. Which is potentially costly, and the benefits are not clear. We could consider adding new `.glob` properties with this behavior to avoid impacting existing users. For that we need to understand better the practical need for such feature. Can you please explain?

**Comment by chaochichen** [comment]
When I went through the exercise to create a sonar-project.properties, I saw some examples of using glob patterns in `sonar.exclusions`. I thought that was very useful and tried to apply to sonar.sources, sonar.jacoco.reportPaths, sonar.scala.coverage.reportPaths, etc. but they didn't work. It appears that the expansion of the glob pattern for sonar.exclusions is done in the embedded scanner, not in the cli.

One of the benefits of using glob patterns for the particular properties that I addressed in this PR is that when the project source code/modules change, there is no need to add the new jacoco.exec or scoverage.xml in the sonar-project.properties. The glob patterns cover the work.

By the way, the added code changes here is backward compatible with those properties. The properties that don't use glob patterns remain functional. As a matter of fact, those properties can mix with glob patterns and relative/absolute paths. E.g.:  `sonar.sources=kubernetes, integration-tests, **/src/main` will work just fine.

**Comment by janos-ss** [comment]
I didn't mean that there is a backward compatibility issue. I meant this change replaces a low-cost operation (list of fixed paths) with a more expensive operation (directory tree traversal).

> One of the benefits of using glob patterns for the particular properties that I addressed in this PR is that when the project source code/modules change, there is no need to add the new jacoco.exec or scoverage.xml in the sonar-project.properties.

I think changing the project structure is a rare event in the lifetime of most projects. In such events, it's fully expected that elements of the tool chain need to be reviewed to adapt to the change. And so to me it seems normal that I have to update the report paths and others in such rare events. If a flexible configuration makes this easier, that's nice, but it fixes only a minor inconvenience.

All in all, I don't think a minor convenience justifies adding a directory tree traversal on every analysis. Current users with large working trees may experience slower scanner runs, and rightfully wonder: *why does the scanner suddenly do that, even though I specified fixed paths as always*?

As mentioned earlier, we could avoid such negative experience by introducing this feature in a new property. However, the use case you described so far doesn't seem very useful: the benefit is small, and I expect the number of real-life use cases to be few. We make it a conscious effort to make sure that every feature we add is of high value, in order to avoid polluting the code with unnecessary complexity. I hope this makes sense to you.

**Comment by chaochichen** [comment]
I'll just use this modified version of sonar-scanner for the projects within my company. Thanks for the feedbacks.

**Pull request closed without merging**
